# Generated by Django 5.0.3 on 2024-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('tapirus', models.BooleanField(default=False)),
                ('goat', models.BooleanField(default=False)),
                ('owl', models.BooleanField(default=False)),
                ('kangaroo', models.BooleanField(default=False)),
                ('badger', models.BooleanField(default=False)),
                ('limit', models.IntegerField()),
                ('dkim', models.CharField(max_length=100)),
            ],
        ),
    ]
